### PR TITLE
removed Shruum wallet as it has been abandoned

### PR DESCRIPTION
**Pull request by jahway603**
removed Shruum wallet as it has been abandoned

### CODE REVIEW

**Comment by jahway603** [comment]
@Crypt0-Bear , not sure if you've seen this PR but wanted to submit this since this mobile wallet is now abandoned

**Comment by Crypt0-Bear** [comment]
Hey just saw the notification. The project is abandoned ?

**Comment by jahway603** [comment]
Yeah, the Shruum wallet developer disappeared, shut down his website, shut down his git with all his code, and has not resurfaced. Bummer because it was a really cool fork and looked really promising.

**Comment by Crypt0-Bear** [comment]
Removed it. Hopefully somebody in the community revives it.

**Pull request merged**
